### ISSUE TITLE
Fast when creating, Slow when reading

### ISSUE THREAD

**Issue by Stefdv** [sjones6/gun-mongo-key#2]
`gun-mongo-key` is working, importing 3000 nodes  ( 10 properties each and 7 tags ) without problems, but it is slow when reading them all back  takes about 120ms per node.

**Comment by sjones6** [comment]
@Stefdv Thanks much for the perf tests!

I made some updates and just merged in changes (see PR #3 ).

Also, [README](https://github.com/sjones6/gun-mongo-key) has the stats I was seeing on my machine (specs given there as well).

Please update to `gun-mongo-key` 1.1 and see if this is improved; if not, let me know what you find or close the issue if so. Thanks! :)

**Comment by Stefdv** [comment]
Whoohoo....you nailed it :) Performance is much better...actually performance is great. I can work with this.:)
Closing the issue.
Tx @sjones6 👍
